version: "3"
services:
  halo:
    image: osixia/openldap:1.5.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data/ldap:/var/lib/ldap
      - ./data/slapd.d:/etc/ldap/slapd.d
    ports:
      - ${PANEL_APP_PORT_HTTP}:389
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    labels:  
      createdBy: "Apps"
  
networks:  
  1panel-network:  
    external: true